namespace GardenAI;

public static class BlogPostPublisher
{
    // Emoji badge per provider for visual scanning in the rendered post
    private static readonly Dictionary<string, string> ProviderEmoji = new()
    {
        ["Anthropic"] = "🟣",
        ["OpenAI"]    = "🟢",
    };

    /// <summary>
    /// Generates a comparison Markdown post covering every model that responded.
    /// </summary>
    public static string GenerateMarkdown(WeatherForecast forecast, IEnumerable<ProviderInsight> results, DaylightInfo? daylight = null, SensorSnapshot? sensors = null)
    {
        var all        = results.ToList();
        var successful = all.Where(r => r.Succeeded).ToList();

        var generatedAt  = successful[0].Insight!.GeneratedAt;
        var slug         = generatedAt.ToString("yyyy-MM-dd");
        var friendlyDate = generatedAt.ToString("dddd, d MMMM yyyy");
        var tzLabel      = generatedAt.Offset.Hours == 13 ? "NZDT" : "NZST";

        // One H3 block per successful model
        var modelSections = string.Join(
            "\n\n---\n\n",
            successful.Select(RenderModelSection));

        // Optional note for any models that didn't respond
        var failed       = all.Where(r => !r.Succeeded).ToList();
        var failuresNote = failed.Count > 0
            ? $"\n> ⚠️ {failed.Count} model(s) did not respond: " +
              string.Join(", ", failed.Select(f => $"`{f.ModelName}`")) + "\n"
            : "";

        var modelList = string.Join(", ", all.Select(r => $"`{r.ModelName}`"));

        return $"""
            ---
            title: "Garden Update — {friendlyDate}"
            date: "{slug}"
            description: "{EscapeYaml(TruncateAtWord(successful[0].Insight!.Summary, 160))}"
            tags: [garden, weather, ai-insights]
            ---

            # Garden Update — {friendlyDate}

            > *Daily insights generated from live sensor and weather data{(all.Count > 1 ? $", compared across {all.Count} AI models" : $", powered by {modelList}")}.*
            > *Sensor data from Ecowitt GW1200 · Weather from [Open-Meteo](https://open-meteo.com) · Dunedin, NZ*

            ---

            {(sensors is not null ? FormatSensorTable(sensors) : "")}### 7-Day Weather Forecast{(forecast.IsFrostRisk ? " — ⚠️ Frost risk in next 3 days" : "")}

            {(daylight is not null ? $"> 🌅 Sunrise: {daylight.SunriseLocal} · Sunset: {daylight.SunsetLocal} · Day length: **{daylight.DayLengthHours:F1} hrs**\n\n" : "")}| Date | Max | Min | Rain | Rain% | Wind | UV | ET₀ | Radiation |
            |------|-----|-----|------|-------|------|-----|------|-----------|
            {string.Join("\n", forecast.Days.Select(d =>
                $"| {d.Date} | {d.TempMaxCelsius:F1}°C | {d.TempMinCelsius:F1}°C | {d.PrecipitationMm:F1}mm | {d.PrecipProbPct}% | {d.WindspeedKph:F0}kph | {d.UvIndex:F1} | {d.Et0Mm:F1}mm | {d.ShortwaveRadiationMjm2:F1}MJ/m² |"))}

            *Generated at {generatedAt:h:mm tt} {tzLabel}*

            ---

            ## AI Model Comparison
            {failuresNote}
            {modelSections}

            ---

            *This post was auto-generated by the Garden AI pipeline.
            Weather data from Open-Meteo · Claude & GPT insights · Built with Astro*
            """;
    }

    private static string RenderModelSection(ProviderInsight result)
    {
        var emoji   = ProviderEmoji.GetValueOrDefault(result.ProviderName, "🔵");
        var insight = result.Insight!;

        var varietyWatch = !string.IsNullOrWhiteSpace(insight.VarietyWatch)
            ? $"\n**Variety Watch**\n\n{insight.VarietyWatch}\n"
            : "";
        var horticulture = !string.IsNullOrWhiteSpace(insight.Horticulture)
            ? $"\n**Horticulture**\n\n{insight.Horticulture}\n"
            : "";

        return $"""
            ### {emoji} {result.ProviderName} — `{result.ModelName}`

            {insight.Summary}

            **Observations**

            {insight.Observations}

            **Actions for Today**

            {insight.Actions}
            {varietyWatch}
            **Looking Ahead**

            {insight.ForecastAdvice}
            {horticulture}
            *{insight.GardenersNote}*
            """;
    }

    private static string FormatSensorTable(SensorSnapshot s)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("### Live Sensor Readings (Ecowitt)");
        sb.AppendLine();
        sb.AppendLine("| Sensor | Value |");
        sb.AppendLine("|--------|-------|");

        if (s.Outdoor is { } o)
        {
            sb.AppendLine($"| Outdoor temp | {V(o.TemperatureC, "°C")} (feels like {V(o.FeelsLikeC, "°C")}) |");
            sb.AppendLine($"| Outdoor humidity | {V(o.Humidity, "%", "F0")} |");
            sb.AppendLine($"| Dew point | {V(o.DewPointC, "°C")} |");
        }

        foreach (var soil in s.SoilChannels)
            sb.AppendLine($"| Soil moisture (ch{soil.Channel}) | {V(soil.MoisturePct, "%", "F0")} |");

        if (s.Wind is { } w)
            sb.AppendLine($"| Wind | {V(w.SpeedKph, " km/h")} (gusts {V(w.GustKph, " km/h")}) |");

        if (s.Rainfall is { } r)
            sb.AppendLine($"| Rain today | {V(r.DailyMm, "mm")} |");

        if (s.Solar is { } sol)
        {
            sb.AppendLine($"| Solar radiation | {V(sol.RadiationWm2, " W/m²", "F0")} |");
            sb.AppendLine($"| UV index | {V(sol.UvIndex, "", "F0")} |");
        }

        if (s.Pressure is { } p)
            sb.AppendLine($"| Pressure | {V(p.RelativeHpa, " hPa")} |");

        static string V(double? v, string unit, string fmt = "F1") =>
            v.HasValue ? $"{v.Value.ToString(fmt)}{unit}" : "n/a";

        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
        return sb.ToString();
    }

    public static async Task SavePostAsync(
        WeatherForecast forecast,
        IEnumerable<ProviderInsight> results,
        string outputDirectory,
        DaylightInfo? daylight = null,
        SensorSnapshot? sensors = null)
    {
        var successful = results.Where(r => r.Succeeded).ToList();
        if (successful.Count == 0)
            throw new InvalidOperationException("No successful insights to publish.");

        Directory.CreateDirectory(outputDirectory);
        var date     = successful[0].Insight!.GeneratedAt;
        var filename = Path.Combine(outputDirectory, $"{date:yyyy-MM-dd}.md");
        var markdown = GenerateMarkdown(forecast, results, daylight, sensors);
        await File.WriteAllTextAsync(filename, markdown);
        Console.WriteLine($"✅ Blog post saved: {filename}");
    }

    private static string EscapeYaml(string s) =>
        s.Replace("\"", "'").Replace("\n", " ").Trim();

    private static string TruncateAtWord(string s, int maxLength)
    {
        s = s.Replace("\n", " ").Trim();
        if (s.Length <= maxLength) return s;
        var cut = s.LastIndexOf(' ', maxLength);
        return cut > 0 ? s[..cut].TrimEnd() + "…" : s[..maxLength] + "…";
    }
}
