namespace GardenAI;

public static class BlogPostPublisher
{
    // Emoji badge per provider for visual scanning in the rendered post
    private static readonly Dictionary<string, string> ProviderEmoji = new()
    {
        ["Anthropic"] = "🟣",
        ["OpenAI"]    = "🟢",
    };

    /// <summary>
    /// Generates a comparison Markdown post covering every model that responded.
    /// </summary>
    public static string GenerateMarkdown(SensorReading reading, WeatherForecast forecast, IEnumerable<ProviderInsight> results)
    {
        var all        = results.ToList();
        var successful = all.Where(r => r.Succeeded).ToList();

        var generatedAt  = successful[0].Insight!.GeneratedAt;
        var slug         = generatedAt.ToString("yyyy-MM-dd");
        var friendlyDate = generatedAt.ToString("dddd, d MMMM yyyy");
        var timeStr      = generatedAt.ToString("h:mm tt");

        var soil1Status = SoilStatusLabel(reading.SoilChannel1.MoisturePercent);
        var soil2Status = SoilStatusLabel(reading.SoilChannel2.MoisturePercent);

        // One H3 block per successful model
        var modelSections = string.Join(
            "\n\n---\n\n",
            successful.Select(RenderModelSection));

        // Optional note for any models that didn't respond
        var failed       = all.Where(r => !r.Succeeded).ToList();
        var failuresNote = failed.Count > 0
            ? $"\n> ⚠️ {failed.Count} model(s) did not respond: " +
              string.Join(", ", failed.Select(f => $"`{f.ModelName}`")) + "\n"
            : "";

        var modelList = string.Join(", ", all.Select(r => $"`{r.ModelName}`"));

        return $"""
            ---
            title: "Garden Update — {friendlyDate}"
            date: {slug}
            description: "{EscapeYaml(successful[0].Insight!.Summary.Split('.')[0])}."
            tags: [garden, sensors, ai-insights]
            ---

            # Garden Update — {friendlyDate}

            > *Daily insights generated from live sensor data and compared across {all.Count} AI models: {modelList}.*
            > *Sensor network: Ecowitt GW1200 gateway · WH51 soil moisture sensors · WN32 outdoor temp/humidity.*

            ---

            ## Today's Conditions

            | Sensor | Reading |
            |--------|---------|
            | 🌡️ Temperature | {reading.Outdoor.TemperatureCelsius}°C (feels like {reading.Outdoor.FeelsLikeCelsius}°C) |
            | 💧 Humidity | {reading.Outdoor.HumidityPercent}% |
            | 🌫️ Dew Point | {reading.Outdoor.DewPointCelsius}°C |
            | 🪴 {reading.SoilChannel1.ChannelName} | {reading.SoilChannel1.MoisturePercent}% {soil1Status} |
            | 🪴 {reading.SoilChannel2.ChannelName} | {reading.SoilChannel2.MoisturePercent}% {soil2Status} |

            *Recorded at {timeStr} NZST*

            ### 7-Day Weather Forecast{(forecast.IsFrostRisk ? " — ⚠️ Frost risk in next 3 days" : "")}

            | Date | Max | Min | Rain | Rain% | Wind | UV |
            |------|-----|-----|------|-------|------|----|
            {string.Join("\n            ", forecast.Days.Select(d =>
                $"| {d.Date} | {d.TempMaxCelsius:F1}°C | {d.TempMinCelsius:F1}°C | {d.PrecipitationMm:F1}mm | {d.PrecipProbPct}% | {d.WindspeedKph:F0}kph | {d.UvIndex:F1} |"))}

            *Forecast from [Open-Meteo](https://open-meteo.com) · Dunedin, NZ*

            ---

            ## AI Model Comparison
            {failuresNote}
            {modelSections}

            ---

            *This post was auto-generated by the Garden AI pipeline.
            Sensor data is collected every 5 minutes; insights are generated and compared across models once daily.*
            """;
    }

    private static string RenderModelSection(ProviderInsight result)
    {
        var emoji   = ProviderEmoji.GetValueOrDefault(result.ProviderName, "🔵");
        var insight = result.Insight!;

        return $"""
            ### {emoji} {result.ProviderName} — `{result.ModelName}`

            {insight.Summary}

            **Observations**

            {insight.Observations}

            **Actions for Today**

            {insight.Actions}

            **Looking Ahead**

            {insight.ForecastAdvice}

            *{insight.GardenersNote}*
            """;
    }

    public static async Task SavePostAsync(
        SensorReading reading,
        WeatherForecast forecast,
        IEnumerable<ProviderInsight> results,
        string outputDirectory)
    {
        var successful = results.Where(r => r.Succeeded).ToList();
        if (successful.Count == 0)
            throw new InvalidOperationException("No successful insights to publish.");

        Directory.CreateDirectory(outputDirectory);
        var date     = successful[0].Insight!.GeneratedAt;
        var filename = Path.Combine(outputDirectory, $"{date:yyyy-MM-dd}.md");
        var markdown = GenerateMarkdown(reading, forecast, results);
        await File.WriteAllTextAsync(filename, markdown);
        Console.WriteLine($"✅ Blog post saved: {filename}");
    }

    private static string SoilStatusLabel(int moisture) => moisture switch
    {
        < 30 => "🔴 Dry — water needed",
        < 45 => "🟡 Getting dry",
        < 70 => "🟢 Good",
        _    => "💦 Very moist"
    };

    private static string EscapeYaml(string s) =>
        s.Replace("\"", "'").Replace("\n", " ").Trim();
}
