#!/usr/bin/env node
// Backfills the `description` frontmatter field in existing posts with a
// one-sentence narrative teaser generated by Claude Haiku.

import Anthropic from '@anthropic-ai/sdk';
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';

const POSTS_DIR = new URL('../site/src/content/posts', import.meta.url).pathname;

const client = new Anthropic();

function extractSummary(content) {
  // First paragraph after a model section heading (e.g. "### 🟢 OpenAI — `...`")
  const match = content.match(/### .+\n\n([\s\S]+?)(?=\n\n\*\*Observations\*\*|\n\n---)/);
  return match ? match[1].trim() : null;
}

function patchDescription(content, teaser) {
  return content.replace(
    /^description: ".*"$/m,
    `description: "${teaser.replace(/"/g, "'")}"`
  );
}

async function generateTeaser(summary) {
  const msg = await client.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 120,
    messages: [{
      role: 'user',
      content: `You are writing a one-sentence narrative hook for a garden blog index page.

Given this summary of today's garden conditions, write a single evocative sentence that reads like the opening of a short chapter — specific, atmospheric, with a sense of tension or turning point. Name a crop or condition. No bullet points, no markdown formatting. Output only the sentence, nothing else.

Summary:
${summary}`
    }]
  });
  return msg.content[0].text.trim();
}

const files = readdirSync(POSTS_DIR)
  .filter(f => f.endsWith('.md'))
  .sort();

console.log(`Found ${files.length} posts to backfill.\n`);

for (const file of files) {
  const path = join(POSTS_DIR, file);
  const content = readFileSync(path, 'utf8');
  const summary = extractSummary(content);

  if (!summary) {
    console.log(`⚠️  ${file}: no Summary section found, skipping.`);
    continue;
  }

  try {
    const teaser = await generateTeaser(summary);
    const updated = patchDescription(content, teaser);
    writeFileSync(path, updated);
    console.log(`✅ ${file}\n   ${teaser}\n`);
  } catch (err) {
    console.error(`❌ ${file}: ${err.message}`);
  }
}
